[project]
name = "msfw"
version = "1.0.0"
dependencies = [
    "flask",
    "pydantic",
    "pika"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
exclude = ["main.py"]